### PR TITLE
added support to split i18n files into multiple json files 

### PR DESCRIPTION
**Pull request by ErikApption**
We have adopted the i18n structure for several projects but as the projects expand, our json files become unmanageable. This patch enables to split the massive files into multiple - e.g. by domain - to be able to manage each file separately.

Added unit tests, and example where the temperature localization is split into multiple files.

### CODE REVIEW

**Comment by ErikApption** [comment]
@AlexTeixeira  Hey Alex - any chances you could have a look? thanks!!

**Comment by AlexTeixeira** [comment]
I look this today

**Comment by AlexTeixeira** [comment]
published : https://www.nuget.org/packages/Askmethat.Aspnet.JsonLocalizer/3.2.0-alpha.1

**Comment by ErikApption** [comment]
Thanks :-)

**Pull request merged**
