### PR TITLE
Collect missing to json

### PR DESCRIPTION
**Pull request by ErikApption**
Added new option MissingTranslationLogBehavior = MissingTranslationLogBehavior.CollectToJSON that enables to track all the missing translations and write them on dispose into a json file. 

The objective of this change is to simplify the process for translating an app. If you run the native language through the localizer (instead of keys), write this to json, you can generate almost all the localized text automatically.

### CODE REVIEW

**Comment by ErikApption** [comment]
@AlexTeixeira  Hi Alex, any chances you could also look at this one? :-)

**Comment by AlexTeixeira** [comment]
Should I merge this one or should we look at your todo first ?

**Comment by ErikApption** [comment]
@AlexTeixeira that should be it for my todo list lol, go ahead and merge this one if that works. The only other minor improvement I was thinking of is to add the option to output the missing keys to console as well instead of a json file but file is probably more practical.

**Comment by AlexTeixeira** [comment]
Let's go ! I comment this thread with the nuget link. Thanks for the 2 PR you made 😃

**Comment by AlexTeixeira** [comment]
It's live : https://www.nuget.org/packages/Askmethat.Aspnet.JsonLocalizer/3.2.0-alpha.3

**Pull request merged**
