### PR TITLE
fixed i18n sample project

### PR DESCRIPTION
**Pull request by ErikApption**
small fixes to enable the blazor project to run

### CODE REVIEW

**Comment by ErikApption** [comment]
Added a second json file in the sample application

**Comment by ErikApption** [comment]
Sorry for all the pull requests but the last one fixes a NPE when there is no neutral file for current language

**Comment by ErikApption** [comment]
Ignore the close above - wrong button

**Comment by ErikApption** [comment]
Sorry for all the pull requests but the last one fixes a NPE when there is no neutral file for current language. Also pressed wrong button

**Comment by AlexTeixeira** [comment]
Don't worry :). You participate and push some's fixes to the project is the most important :)

**Pull request merged**
